# this is the workflow name
name: hello workflow

# this is the trigger
on:
  push:
    branches: [main]

# jobs
#hehehehehe
jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: say hello to users
        run: echo "Hello This is Gagan saying hello"

      - name: say again hello
        run: echo "Gagan is the king"
